name: Flutter-Code-Check

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'master'
          flutter-version: '3.7.1'
          cache: true
          
      - name: run Flutter doctor
        run: flutter doctor -v
        
      - name: run pub get
        run: flutter pub get
        
      - name: run analyze
        run: flutter analyze
        
      - name: run test
        run: flutter test
